analysis_name: "AZHTo2NuTTbar"

# Source: https://twiki.cern.ch/twiki/bin/viewauth/CMS/TWikiLUM, in units of [pb-1]
target_lumis:
  UL18: "59830"
  UL17: "41480"
  UL16postVFP: "19500" # "36330"
  UL16preVFP: "16800" # "36330"

config_parse:
  mail: "lukas@me.com"
  notification: "Error"

cycle:
  name: "uhh2::AnalysisModuleRunner"
  output_subdirs:
    Preselection: "output_01_preselection/"
    Reconstruction: "output_02_reconstruction/"

user_config:
  PrimaryVertexCollection: "offlineSlimmedPrimaryVertices"
  ElectronCollection: "slimmedElectronsUSER"
  MuonCollection: "slimmedMuonsUSER"
  JetCollection: "jetsAk4CHS"
  GenParticleCollection: "GenParticles"
  GenJetCollection: "slimmedGenJets"
  METName: "slimmedMETs"
  use_sframe_weight: "false"
  jersmear_direction: "nominal"
  jecsmear_direction: "nominal"
  is_puppy: "true"
  Sys_PU: "central"
  lumihists_lumi_per_bin: "500.0"
  gen_level: "false"
  PrimaryDataset: ""
  ScaleVariationMuF: "nominal"
  ScaleVariationMuR: "nominal"
  VJetsReweighting_do_EWK: "true"
  VJetsReweighting_do_QCD_EWK: "false"
  VJetsReweighting_do_QCD_NLO: "true"
  VJetsReweighting_do_QCD_NNLO: "false"
  apply_TopPtReweighting: "true"
  # Custom key-value pairs: further processed in generator
  BTagMCEffFile: ""
  BTagScaleFactorCSV: ""
  lumi_file: ""
  additionalBranches:
    - "tight_b"
    - "event_weight"
    - "channel"
    - "region"
    - 'weight_murmuf_downdown'
    - 'weight_murmuf_downnone'
    - 'weight_murmuf_dyn1_downdown'
    - 'weight_murmuf_dyn1_downnone'
    - 'weight_murmuf_dyn1_nonedown'
    - 'weight_murmuf_dyn1_noneup'
    - 'weight_murmuf_dyn1_upnone'
    - 'weight_murmuf_dyn1_upup'
    - 'weight_murmuf_dyn2_downdown'
    - 'weight_murmuf_dyn2_downnone'
    - 'weight_murmuf_dyn2_nonedown'
    - 'weight_murmuf_dyn2_noneup'
    - 'weight_murmuf_dyn2_upnone'
    - 'weight_murmuf_dyn2_upup'
    - 'weight_murmuf_dyn3_downdown'
    - 'weight_murmuf_dyn3_downnone'
    - 'weight_murmuf_dyn3_nonedown'
    - 'weight_murmuf_dyn3_noneup'
    - 'weight_murmuf_dyn3_upnone'
    - 'weight_murmuf_dyn3_upup'
    - 'weight_murmuf_dyn4_downdown'
    - 'weight_murmuf_dyn4_downnone'
    - 'weight_murmuf_dyn4_nonedown'
    - 'weight_murmuf_dyn4_noneup'
    - 'weight_murmuf_dyn4_upnone'
    - 'weight_murmuf_dyn4_upup'
    - 'weight_murmuf_nonedown'
    - 'weight_murmuf_noneup'
    - 'weight_murmuf_upnone'
    - 'weight_murmuf_upup'
    - 'weight_toppt'
    - 'weight_toppt_a_down'
    - 'weight_toppt_a_up'
    - 'weight_toppt_applied'
    - 'weight_toppt_b_down'
    - 'weight_toppt_b_up'
    - 'weight_vjets_EWK'
    - 'weight_vjets_QCD_EWK'
    - 'weight_vjets_QCD_NLO'
    - 'weight_vjets_QCD_NNLO'
    - 'weight_vjets_applied'
