# DrellYan:
  # DYJetsToNuNu not NTuplized yet. TODO!
QCD:
  - QCD_HT50to100
  - QCD_HT100to200
  - QCD_HT200to300
  - QCD_HT300to500
  - QCD_HT500to700
  - QCD_HT700to1000
  - QCD_HT1000to1500
  - QCD_HT1500to2000
  - QCD_HT2000toInf
SingleTop:
  - ST_s-channel_4f_leptonDecays  # hdamp not centrally available - no powheg?
  - ST_t-channel_antitop_4f_InclusiveDecays  # hdamp centrally available, but not produced
  - ST_t-channel_top_4f_InclusiveDecays  # hdamp centrally available, but not produced
  - ST_tW_antitop_5f_inclusiveDecays  # hdamp not centrally available
  - ST_tW_top_5f_inclusiveDecays  # hdamp not centrally available
TT:
  - {nominal: TTToHadronic, hdampUp: TTToHadronic_hdampUP, hdampDn: TTToHadronic_hdampDOWN, tuneUp: TTToHadronic_TuneCP5up, tuneDown: TTToHadronic_TuneCP5down}
  - {nominal: TTToSemiLeptonic, hdampUp: TTToSemiLeptonic_hdampUP, hdampDn: TTToSemiLeptonic_hdampDOWN, tuneUp: TTToSemiLeptonic_TuneCP5up, tuneDown: TTToSemiLeptonic_TuneCP5down}
  - {nominal: TTTo2L2Nu, hdampUp: TTTo2L2Nu_hdampUP, hdampDn: TTTo2L2Nu_hdampDOWN, tuneUp: TTTo2L2Nu_TuneCP5up, tuneDown: TTTo2L2Nu_TuneCP5down}
TTV:
  - TTZToLLNuNu_M-10_TuneCP5
  - TTZToQQ_TuneCP5
  - TTWJetsToLNu_TuneCP5
  - TTWJetsToQQ_TuneCP5
VV:
  - ZZ
  - WW
  - WZ
WJets:
  - WJetsToLNu_HT-70to100
  - WJetsToLNu_HT-100to200
  - WJetsToLNu_HT-200to400
  - WJetsToLNu_HT-400to600
  - WJetsToLNu_HT-600to800
  - WJetsToLNu_HT-800to1200
  - WJetsToLNu_HT-1200to2500
  - WJetsToLNu_HT-2500toInf
ZJets:
  - "ZJetsToNuNu_HT-2500toInf"
  - "ZJetsToNuNu_HT-1200to2500"
  - "ZJetsToNuNu_HT-800to1200"
  - "ZJetsToNuNu_HT-600to800"
  - "ZJetsToNuNu_HT-400to600"
  - "ZJetsToNuNu_HT-200to400"
  - "ZJetsToNuNu_HT-100to200"