years:
  - UL17

backgrounds:
  - TT
  - TTZ
  - SingleTop
  - TTW
  - VV
  - QCD
  - WJets_ljet
  - WJets_bjet
  - DYJets_ljet
  - DYJets_bjet

svars:
  - MET
  - m_H
  - mt_A
  #- mt_H


branches:
  - event_weight
  - region

#region_branch: region

variations:
  weight_btag: ["_central", "_bc_up", "_bc_down"]
  weight_btag_: ["central", "light_up", "light_down"]
  weight_pu: ["", "_up", "_down"]
  weight_puid_sf: ["", "_up", "_down"]
  #weight_sfelec_reco: ["", "_up", "_down"]
  #weight_sfelec_tight_id: ["", "_up", "_down"]
  #weight_sfmu_isolation: ["", "_up", "_down"]
  #weight_sfmu_tight_id: ["", "_up", "_down"]
  #weight_sfmu_reco: ["", "_up", "_down"]
  #weight_trigger_sf_ee: ["", "_up", "_dn"]
  #weight_trigger_sf_emu: ["", "_up", "_dn"]
  #weight_trigger_sf_mumu: ["", "_up", "_dn"]
  weight_toppt_a: ["", "_up", "_down"]
  weight_toppt_b: ["", "_up", "_down"]
  weight_isr_2: ["_up", "_down"]
  weight_fsr_2: ["_up", "_down"]
  weight_muf: ["_noneup", "_nonedown"]
  weight_mur: ["_upnone", "_downnone"]
  weight_murmuf: ["_upup", "_downdown"]
  weight_pdf: ["", "_up", "_down"]
  weight_vjets_EWK: ["", "_d1K", "_d2K", "_d3K"]
  weight_vjets_QCD_NLO: ["", "_d1K", "_d2K", "_d3K"]

sample_variations:
  foo: []

sample_var_whitelist:
  foo: []

angle_cut:
  active: False
  signal_efficiency: 0.9

dnn_cut:
  active: False
  signal_efficiency: 0.9