years:
  - UL17

backgrounds:
  - TT
  - TTZ
  - SingleTop
  - TTW
  - VV
  - QCD
  - WJets
  - ZJets

svars:
  - A_mt
  - H_mt
  - MET

branches:
  - event_weight

region_branch: 
  - SignalRegion

#based on scale factors
variations:

#hdamp, cptune
sample_variations:

sample_var_whitelist:
  Total: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  Absolute: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  Absolute_YEAR: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  BBEC1: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  BBEC1_YEAR: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  EC2: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  EC2_YEAR: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  FlavorQCD: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  HF: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  HF_YEAR: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  RelativeBal: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  RelativeSample_YEAR: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  jer: ["AtoZH", "DYJets", "TT", "TTZ", "SingleTop", "TTW", "VV", "WJets", "QCD"]
  hdamp: ["TT"]
  TuneCP5: ["TT"]

angle_cut:
  active: False
  signal_efficiency: 0.9

dnn_cut:
  active: False
  signal_efficiency: 0.9
